### ISSUE TITLE
Asset licenses?

### ISSUE THREAD

**Issue by kozross** [Aerolab/tetris.js#11]
Are your assets licensed the same way as your code, or differently?

**Comment by RobertoGonzalez** [comment]
@kozross Which assets do you mean? Everything we built is MIT licensed (library, blocks, etc), but I want to double check just in case.

**Comment by kozross** [comment]
'Assets' in regard to a game usually refers to things like art, sound effects, etc.

**Comment by RobertoGonzalez** [comment]
Yup, those are MIT as well (except for sound effects, but the current release doesn't have any).
