### ISSUE TITLE
Speeding up the game

### ISSUE THREAD

**Issue by t9creative-zz** [Aerolab/tetris.js#17]
Is there a way to speed up the game after a certain number of lines have been reached?

**Comment by RobertoGonzalez** [comment]
@t9creative You'd need to tweak the source code a bit, since the number of lines is fixed to speed up every 10 lines.
This is done in this line of the source code (just change the 10 to the value you want): https://github.com/Aerolab/blockrain.js/blob/gh-pages/src/blockrain.jquery.src.js#L596
