### ISSUE TITLE
Assistance with triggering controls

### ISSUE THREAD

**Issue by TheLittleDoc** [Aerolab/tetris.js#27]
Hi there! I'm not hopeful I'll get a reply seeing as the last issue was over a year ago, but I recently have been attempting to integrate blockrain into a programming project concerning a sandbox VR game called Anyland. Anyland has in-game webscreens that allow you to pass in-game triggers through to the website using the JavaScript function AnylandTold. Proper usage looks like this:
`function AnylandTold(tell, isAuthority) {
     //function goes here, usually if...else... with tell
}`

I can not for the life of me figure out how to trigger the controls for blockrain using this system! Can anyone offer me some assistance? I'd like to just do a 'if(tell == 'right') {moveRight(true)}' but I get the feeling that won't work. Please let me know!

**Comment by RobertoGonzalez** [comment]
You'll probably need to modify the source code for this to work. If I'm remembering correctly how jquery works, you should be able to implement a few top level methods for movement (at the same level as [start()](https://github.com/Aerolab/blockrain.js/blob/gh-pages/src/blockrain.jquery.src.js#L41) for example). 
For example, adding a function `moveRight()` that calls `game._board.cur.moveRight()` (the same goes for Left and Down).

Once you have those methods you should be able to call them with `$game.blockrain('moveRight')` from outside the game code.
