### ISSUE TITLE
Where are the controls?

### ISSUE THREAD

**Issue by Farbmond** [Aerolab/tetris.js#28]
I can't figure out how to activate the touch controls. I tried with
$ game.blockrain ('controls', true);
$ game.blockrain ('touchcontrols', true);
But no buttons appear next to the playing field. Swiping or typing doesn't work either. I can't control the game on touch screens.

**Comment by RobertoGonzalez** [comment]
The plugin adds a few unstyled links inside the playing field with the `.blockrain-touch` class for movement and rotation, but you need to style them with a bit of CSS in order to see and use them. Turning them into 50px circles and positioning them with `position:absolute` should do the trick.
