### ISSUE TITLE
Responsiv and Speed

### ISSUE THREAD

**Issue by orcen** [Aerolab/tetris.js#5]
Hi, great script, i like it a lot.

Question 1: how to use it on mobile? is it possible now?
Question 2: will there be a possibility to change the speed during the game?

We want to use it on our 404 Site, can we do it? Is it enough we link to your page as author of the script?

**Comment by sbehrends** [comment]
1: Sorry, there is no gesture binded yet for mobile or any kind of way to play without keyboard.
2: Probably @RobertoGonzalez can answer this :)

Sure you can use it and give author credits :)

Have fun!

**Comment by RobertoGonzalez** [comment]
@orcen Thanks for the comments! Yes, you can update the settings during the game by doing

`$game.blockrain({ speed: 1 });`

This works with pretty much any of the [settings](https://github.com/Aerolab/blockrain.js#options) as well.
On mobile, the only thing I'd suggest is to try not to resize the game area (when going from portrait to landscape, for instance), as the game becomes stretched. Most of the fixes for that have some big downside -like deleting blocks- so it's an open issue.
